### ISSUE TITLE
Feature Request: client_credentials

### ISSUE THREAD

**Issue by klausbreyer** [MichaelJamesParsons/ustream-nodejs-sdk#11]
For serverside applications, it would be nice if https://developers.video.ibm.com/channel-api/getting-started.html#client-credentials-flow_11 is supported as well.

**Comment by MichaelJamesParsons** [comment]
I appreciate your interest. I'm actually taking a two week vacation starting tomorrow, but I'll look into this as soon as I get back.

If this feature is an immediate blocker, please consider creating a pull request.

**Comment by MichaelJamesParsons** [comment]
Quick update, I have not forgotten about this request. I return from vacation July 7 and will look into it shortly after.

**Comment by MichaelJamesParsons** [comment]
I've returned from vacation. I will be looking into this further this week.

**Comment by CBurton1** [comment]
Any update on when this will be implemented?

**Comment by MichaelJamesParsons** [comment]
This is now available in `v1.8.0`
