### ISSUE TITLE
Feature Request: Access to the playlist api

### ISSUE THREAD

**Issue by CBurton1** [MichaelJamesParsons/ustream-nodejs-sdk#12]
v1.2.2 does not have access to the playlist API.

I notice it is under the TODO list, do you have a timeline when this will be available?

**Comment by MichaelJamesParsons** [comment]
The playlist API is now released as v1.3.0. I have plans to make significant changes in the upcoming months. See [the project description](https://github.com/MichaelJamesParsons/ustream-nodejs-sdk/projects) for details.
