### ISSUE TITLE
Error: playlist.create returns 400

### ISSUE THREAD

**Issue by CBurton1** [MichaelJamesParsons/ustream-nodejs-sdk#13]
I am getting an error back when trying to create a playlist on my channel.

I am passing both my channelId (which does exist and is the correct id)
and a title for my playlist to the 
`ustream.playlist.create` method.

The response I get back from the api is 

Request failed with status code 400
statusText:"Bad Request"

I am able to use any of the other methods on the playlist API, listing them, add videos to existing playlists etc.

Is there any issue with the api creating playlists or is there something I am not doing correctly when trying to create a playlist?

**Comment by CBurton1** [comment]
@MichaelJamesParsons It looks like the create method has an error with the qs.stringify.

lib/api/playlist line 77

qs.stringify expects an object.

When I updated that it created the playlist, but the response was an empty array so it failed on line 78

**Comment by MichaelJamesParsons** [comment]
Looks like this was an oversight from a previous community contribution. I'll upload a fix after business hours tonight.

**Comment by MichaelJamesParsons** [comment]
Fixed in #14 and published in a new release.
