### ISSUE TITLE
Feature Request: Custom Metadata endpoints

### ISSUE THREAD

**Issue by CBurton1** [MichaelJamesParsons/ustream-nodejs-sdk#18]
It would be great to be able to add custom metadata from your TODO list! If I can be of any help in developing this just let me know! So far you've been really quick to implement

Thanks!

**Comment by MichaelJamesParsons** [comment]
No problem, I'll add metadata support this weekend.

**Comment by MichaelJamesParsons** [comment]
Released in `v1.5.0`.

[Related code](https://github.com/MichaelJamesParsons/ustream-nodejs-sdk/blob/master/lib/api/custom_metadata.js)
