### ISSUE TITLE
Feature Request?: Custom metadata on upload for video

### ISSUE THREAD

**Issue by CBurton1** [MichaelJamesParsons/ustream-nodejs-sdk#20]
Thanks for implementing the custom metadata endpoints over the weekend.

Once custom metadata is added to your channel, is it possible when uploading a video to add the custom metadata to it? 

If I create a custom metadata field and make it mandatory, then when I upload (which doesn't allow the possibility to add the metadata, it would most likely fail to upload?)

**Comment by CBurton1** [comment]
Specifically this endpoint: 
https://developers.video.ibm.com/channel-api/channel.html#set-video-metadata-value_49

**Comment by MichaelJamesParsons** [comment]
Support for managing custom metadata in videos and channels has been added in #21 (released as `v1.6.0`).

> If I create a custom metadata field and make it mandatory, then when I upload (which doesn't allow the possibility to add the metadata, it would most likely fail to upload?)

I wasn't able to trigger an error while uploading a video to a channel that required metadata. The API documentation doesn't go into great detail about the behavior of required metadata.

If this becomes an issue in the future, please reach out and we can find a solution then.
