### ISSUE TITLE
Receiving a 402 - Payment Required when using user endpoints

### ISSUE THREAD

**Issue by CBurton1** [MichaelJamesParsons/ustream-nodejs-sdk#23]
Trying to list the labels on an account and receiving a 402 - Payment Required error back.

I am using the password strategy to authorize with the API, as far as I know my user has admin access to the account and should be able to list / add labels.

Any insight would be greatly appreciated!

**Comment by MichaelJamesParsons** [comment]
I apologize for the delay. I've been unavailable this past week.

IBM provided me with a development account to test this repository against their API, but the account has some restrictions. I have limited account management access, so I'm unfamiliar with what settings need to change to resolve this issue.

The customer support team should be able to offer more assistance. You can find their phone number in the admin portal.
