### ISSUE TITLE
Feature Request: Modify Video

### ISSUE THREAD

**Issue by CBurton1** [MichaelJamesParsons/ustream-nodejs-sdk#24]
If possible it would be great if this endpoint could be added

https://developers.video.ibm.com/channel-api/channel.html#Edit%20video%20details

**Comment by MichaelJamesParsons** [comment]
Sure, I'll add it over the weekend.

**Comment by MichaelJamesParsons** [comment]
Released in `v1.7.0`

[view code](https://github.com/MichaelJamesParsons/ustream-nodejs-sdk/blob/master/lib/api/video.js#L65)
