### ISSUE TITLE
UnhandledPromiseRejectionWarning - ustream.video.upload

### ISSUE THREAD

**Issue by pooshonbanerjee** [MichaelJamesParsons/ustream-nodejs-sdk#3]
I have tried to include as much information as I could:

---The API call ----- from Angular client via POST ---- printed onto console at server side
/api/upload called with ::  { fieldname: 'fileItem',
  originalname: 'ISAM.mp4',
  encoding: '7bit',
  mimetype: 'video/mp4',
  destination: 'uploads/',
  filename: 'file-XXXXXXXXX-ISAM.mp4',
  path: 'uploads/file-XXXXXXXXX-ISAM.mp4',
  size: 87654066 }  :  { userCnum: 'XXXXXXXXX',
  videoDescription: '',
  videoTitle: 'ISAM',
  videoSection: 'Other Videos',
  videoFile: 'ISAM.mp4' }

---The part from userCnum is used elsewhere ------

Even though upload has a promise, which is handled in a catch block, this error shows up whenever I am trying to upload a file that is 80 MB in size, my real users would upload much bigger files.

(node:20373) UnhandledPromiseRejectionWarning: Error: Error: Unable to make data connection( Error: connect ECONNREFUSED 199.66.237.110:30260)
    at ftp.put (/somepath/node_modules/ustream-sdk/lib/api/video.js:185:20)
    at /somepath/node_modules/ftp/lib/connection.js:957:14
    at Object.cb (/somepath/node_modules/ftp/lib/connection.js:881:11)
    at Parser.<anonymous> (/somepath/node_modules/ftp/lib/connection.js:117:20)
    at emitTwo (events.js:126:13)
    at Parser.emit (events.js:214:7)
    at Parser._write (/somepath/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Parser.Writable.write (_stream_writable.js:290:11)
(node:20373) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20373) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

----- Once this error is thrown, my client end console shows this -------
error ->  Object { headers: Object, status: 0, statusText: "Unknown Error", url: null, ok: false, name: "HttpErrorResponse", message: "Http failure response for (unknown …", error: error }  main.js:1157:13
-----And after a while, the server console shows this -------
ustream video -> { channelId: 23585844, videoId: '115574393' }
------ UStream Dashboard shows the video is uploaded -------
Now this data cannot be used since the call has ended and client has already thrown an error.

I have a few more queries, but I clutter this one, so leaving those for later.

Thanks

Pooshon

**Comment by MichaelJamesParsons** [comment]
I appreciate the report. I'm looking into it.

**Comment by pooshonbanerjee** [comment]
Thanks @MichaelJamesParsons

**Comment by MichaelJamesParsons** [comment]
> Even though upload has a promise, which is handled in a catch block, this error shows up whenever I am trying to upload a file that is 80 MB in size, my real users would upload much bigger files.

@pooshonbanerjee The video upload wasn't listening for FTP connection errors, so when your application unexpectedly disconnected, an uncaught exception was triggered. I corrected the issue so FTP errors are now caught and appropriately passed through the `Promise.catch()` block.

> ...this error shows up whenever I am trying to upload a file that is 80 MB in size

There haven't been any reports of the upload failing for large files in the past. I attempted to reproduce the FTP connection error with a 120MB video and a 475MB video. Both uploaded without a problem.

Could it be a networking issue on your end? Firewall?

### Fixes are on master
Before rolling out a new release, I need to write up some formal unit tests to support the changes I made.   For now, you can access these fixes on `master`. I'll leave this issue open until the next release.

**Comment by pooshonbanerjee** [comment]
Okay, I understand, so I will just download the mater and replace video.js in my package. Are there any other files you made changes to?
Pardon my questions, I am new to GitHub, in fact this is my first ticket ever.

**Comment by MichaelJamesParsons** [comment]
@pooshonbanerjee No worries. Questions are welcome!

There is no need to copy files around. You can install the master branch directly using npm. Inside your `package.json` file, add the following to your `dependencies`:

```
"ustream-sdk": "github:MichaelJamesParsons/ustream-nodejs-sdk#master"
```

Then run `npm update`.

**Comment by pooshonbanerjee** [comment]
Thanks for your prompt response Michael, I however did copy and tried. I am however facing a new issue this time. Only one out of seven tries have succeeded. The issue is 2 FTP requests are created for one upload and hence the response from the server to my client is askew.

Here is what has happened:
![image](https://user-images.githubusercontent.com/40276600/41473824-e9f73a30-70a9-11e8-929a-bd1d44237e73.png)
The top 2 rows are for one request, a file named 'isam 5'. Both completed, but the response returned was of HTTPProgressEvent and not HTTPResponseEvent.
Here is the console.log from server:
```
/api/upload called with ::  { fieldname: 'fileItem',
  originalname: 'ISAM.mp4',
  encoding: '7bit',
  mimetype: 'video/mp4',
  destination: 'uploads/',
  filename: 'file-097788744-ISAM.mp4',
  path: 'uploads/file-097788744-ISAM.mp4',
  size: 87654066 }  :  { userCnum: '097788744',
  videoDescription: 'isam 5',
  videoTitle: 'isam 5',
  videoSection: 'Other Videos',
  videoFile: 'ISAM.mp4' }
ustream video -> { channelId: 23585844, videoId: '115590295' }
video id returned :  115590295
ustream video -> { channelId: 23585844, videoId: '115590330' }
video id returned :  115590330
```

And here is the console.log from the client:
```
upload progress ->  Object { type: 1, loaded: 87654908, total: 87654908 } 

HttpEventType.Response ->  10  |  transfer complete  

msg ->  Object { message: "File "ISAM.mp4" was uploaded succes…", path: "uploads/file-097788744-ISAM.mp4", title: "isam 5", desc: "isam 5" } 

finalize post request created ::  Object { url: "https://localhost:9443/api/finalize/", body: Object, reportProgress: true, withCredentials: false, responseType: "json", method: "POST", headers: Object, params: Object, urlWithParams: "https://localhost:9443/api/finalize/" }  

upload progress ->  Object { type: 1, loaded: 75, total: 75 } 
upload progress ->  Object { type: 1, loaded: 75, total: 75 }

error from finalize video-> Object { headers: Object, status: 0, statusText: "Unknown Error", url: null, ok: false, name: "HttpErrorResponse", message: "Http failure response for (unknown …", error: error } 

finalize :  Http failure response for (unknown url): 0 Unknown Error
```

The only successful upload here (screenshot reference) is row number 3 from top, 'electro 4'. Row number 6 from top, labelled 'ISAM' was uploaded from the dashboard, to check if there is a problem at UStream end, it went fine. 

Row number 3 is a very small 6 mb file, so it completed, here is the client log:

```
upload post request created ::  Object { url: "https://localhost:9443/api/upload/", body: FormData, reportProgress: true, withCredentials: false, responseType: "json", method: "POST", headers: Object, params: Object, urlWithParams: "https://localhost:9443/api/upload/" }  

upload progress ->  Object { type: 1, loaded: 802257, total: 6574120 }  
upload progress ->  Object { type: 1, loaded: 6110673, total: 6574120 }  
upload progress ->  Object { type: 1, loaded: 6574120, total: 6574120 }  

HttpEventType.Response ->  10  |  transfer complete  

msg ->  Object { message: "File "Intro Template 6 - Electro.mp…", path: "uploads/file-097788744-Intro Templa…", title: "electro 4", desc: "electro 4" }  

finalize post request created ::  Object { url: "https://localhost:9443/api/finalize/", body: Object, reportProgress: true, withCredentials: false, responseType: "json", method: "POST", headers: Object, params: Object, urlWithParams: "https://localhost:9443/api/finalize/" }  

upload progress ->  Object { type: 1, loaded: 103, total: 103 }  

HttpEventType.Response ->  40  |  Video processing complete with id[115590278]. Transcoding will run in background, your video will be availble for preview shortly.  

finalize :  Object { message: "Video processing complete with id[1…", videoId: "115590278" } 
```

I would now try your method of installing the package, not sure how much that would help since at least one of the requests went through properly, so I guess the code is fine, but I would still give it a try. 
The other thing I would try is `reportProgress: true` in the finalize POST call.

Will update you, how it went.

**Comment by pooshonbanerjee** [comment]
So, here is what is happening, and btw, I am tracking the ftp upload progress to understand what is happening and when it is happening. Also, I have added a few console.log to understand the flow.

Server log:

```
/api/upload called with ::  { fieldname: 'fileItem',
  originalname: 'ISAM.mp4',
  encoding: '7bit',
  mimetype: 'video/mp4',
  destination: 'uploads/',
  filename: 'file-097788744-ISAM.mp4',
  path: 'uploads/file-097788744-ISAM.mp4',
  size: 87654066 }  :  { userCnum: '097788744',
  videoDescription: 'isam 8',
  videoTitle: 'isam 8',
  videoSection: 'Other Videos',
  videoFile: 'ISAM.mp4' }
api /finalize started executing, next is ustream.video.upload call...
ustream-sdk.upload called
ustream-sdk._initiateUpload called
ustream-sdk._ftpUpload called
binary file mode set
Progress:  0%
Progress:  0%
Progress:  0%
Progress:  0%
Progress:  0%
Progress:  0%
Progress:  1%
Progress:  1%
Progress:  1%
Progress:  1%
Progress:  1%
Progress:  1%
Progress:  1%
Progress:  1%
Progress:  1%
Progress:  1%
Progress:  1%
Progress:  1%
Progress:  1%
Progress:  1%
Progress:  2%
Progress:  2%
Progress:  2%
Progress:  2%

```
So, this goes on for about 2 minutes, and at around 60-70% upload the post is called again...

```
Progress:  69%
Progress:  69%
Progress:  69%
api /finalize started executing, next is ustream.video.upload call...
ustream-sdk.upload called
ustream-sdk._initiateUpload called
Progress:  69%
Progress:  69%
.
.
.
Progress:  71%
ustream-sdk._ftpUpload called
Progress:  71%
.
.
.
Progress:  73%
Progress:  73%
binary file mode set
Progress:  0%
Progress:  0%
Progress:  0%
Progress:  73%
Progress:  73%

```
And the second upload starts from 0%. This is when the client gets the error. I have used shareReplay(1) too, but that didn't work either. I am delving deep, however, it appears to me that connection being slow (around 7mbps upload speed), like you mentioned before and the file being 80mb, crossing a threshold of 2 minutes to upload, (I don't know where it is set, will find out), is causing the post to fire twice. 

I can try the following:
- Push this to Bluemix, run it from there and see how it goes
- Use share() instead of shareReplay(1)
- Check if there are multiple subscriptions, I however doubt that

Will let you know what I find out.

**Comment by pooshonbanerjee** [comment]
This is what I found out when I investigated more, my node server timeout period is 2 minutes, which is the default, and the FTP put takes longer than 2 minutes, so by that time the socket has closed thrown an unknown error to the client and on the other hand angular service executes the post request a second time because it didn't get a response, creating a second FTP upload queue on UStream. 
So what I have done now is res.send(OK) back to the client as soon as ftp put() is fired, and separately check the status. Not a complete success yet, since I am getting:

```
ftp put method has thrown some error
ustream error ->  Error: Timed out while making data connection
    at Timeout.<anonymous> (/somepath/node_modules/ftp/lib/connection.js:901:12)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```
From this part of the code:
```
        ftp.put(stream, ftpDest, (err) => {
          ftp.end()

          if (err) {
            console.log('ftp put method has thrown some error');
            return reject(err)
          }

          return resolve()
        })

```
This however could be a totally isolated and genuine error with the connection. I am trying to find out more. At least the server timeout and duplicate POST request issue is gone. Will let you know more soon.

**Comment by MichaelJamesParsons** [comment]
@pooshonbanerjee What you've demonstrated above doesn't appear to be a bug in the Ustream SDK, but an issue with the implementation of your application code.

> So what I have done now is res.send(OK) back to the client as soon as ftp put() is fired, and separately check the status. 

Two issues with this solution:

1. Behind the scenes, `res.send(OK)` writes your response, then closes the connection. Sending a response *before* `ftp.put()` completes will interrupt your file transfer.

2. `ustream.video.upload()` will only resolve when the upload is complete (or an error is thrown). Which means you would have to change the SDK to signal your application to run `res.send()` before `ftp.put()`.  

    Directly altering third party code is poor practice as it may introduce bugs or unintended side-effects. If you're using the NPM package manager, your changes may be removed after updating or installing packages. I recommend creating a fork of this repository if you intend to make internal changes to the code.

Try extending the request timeout. This [stackoverflow post](https://github.com/MichaelJamesParsons/ustream-nodejs-sdk/issues/3) should point you in the right direction.

**Comment by pooshonbanerjee** [comment]
Hi @MichaelJamesParsons,

I have been busy with my development so could not get back with status on how it went. It works fine locally, all uploads go through, with ftp progress polled. Today I pushed the app to Bluemix and the same UnhandledPromiseRejectionWarning (error)came back, ftp.put didn't work, thought of letting you know. Here is a portion of the log.

```
2018-06-20T21:18:32.47+0530 [APP/PROC/WEB/0] OUT ustream-sdk.upload called
   2018-06-20T21:18:32.47+0530 [APP/PROC/WEB/0] OUT ustream-sdk._initiateUpload called
   2018-06-20T21:18:32.49+0530 [RTR/1] OUT test-object-storage-dev.mybluemix.net - [2018-06-20T15:48:32.447+0000] "POST /api/finalize/ HTTP/1.1" 200 110 191 "https://test-object-storage-dev.mybluemix.net/ustream" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:52.0) Gecko/20100101 Firefox/52.0" "10.84.125.26:26575" "169.47.199.72:63334" x_forwarded_for:"47.15.168.206, 10.84.125.26" x_forwarded_proto:"https" vcap_request_id:"c6fb13c4-1718-4ca7-5a85-5c6b50b771f9" response_time:0.049001741 app_id:"1ce6f29d-5fbe-4d87-ad1a-8e4321044e70" app_index:"0" x_global_transaction_id:"558430383" true_client_ip:"-" x_b3_traceid:"3de0d27a2fddd952" x_b3_spanid:"3de0d27a2fddd952" x_b3_parentspanid:"-"
   2018-06-20T21:18:32.49+0530 [RTR/1] OUT 
   2018-06-20T21:18:32.76+0530 [APP/PROC/WEB/0] ERR (node:57) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
   2018-06-20T21:18:32.77+0530 [APP/PROC/WEB/0] ERR     at createError (/home/vcap/app/node_modules/axios/lib/core/createError.js:16:15)
   2018-06-20T21:18:32.77+0530 [APP/PROC/WEB/0] ERR     at settle (/home/vcap/app/node_modules/axios/lib/core/settle.js:18:12)
   2018-06-20T21:18:32.77+0530 [APP/PROC/WEB/0] ERR     at IncomingMessage.handleStreamEnd (/home/vcap/app/node_modules/axios/lib/adapters/http.js:191:11)
   2018-06-20T21:18:32.77+0530 [APP/PROC/WEB/0] ERR     at emitNone (events.js:111:20)
   2018-06-20T21:18:32.77+0530 [APP/PROC/WEB/0] ERR     at IncomingMessage.emit (events.js:208:7)
   2018-06-20T21:18:32.77+0530 [APP/PROC/WEB/0] ERR     at endReadableNT (_stream_readable.js:1064:12)
   2018-06-20T21:18:32.77+0530 [APP/PROC/WEB/0] ERR     at _combinedTickCallback (internal/process/next_tick.js:138:11)
   2018-06-20T21:18:32.77+0530 [APP/PROC/WEB/0] ERR     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
   2018-06-20T21:18:32.77+0530 [APP/PROC/WEB/0] ERR (node:57) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
   2018-06-20T21:18:32.77+0530 [APP/PROC/WEB/0] ERR (node:57) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

You will understand this better, because I certainly don't.

**Comment by MichaelJamesParsons** [comment]
@pooshonbanerjee Good catch. I'll push up a fix. Since this is not directly related to your original post, please create a separate issue so it can be properly tracked.

**Comment by pooshonbanerjee** [comment]
Will do.
